=== slamgp/xml/xml/xml project/planes.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    
	<xsd:element name="Planes" type="PlanesType"></xsd:element>

       <xsd:complexType name="PlanesType">
          <xsd:sequence>
               <xsd:element name="Plane" type="PlaneType" minOccurs="1" maxOccurs="unbounded"/>
          </xsd:sequence>
       </xsd:complexType>
    	
	<xsd:complexType name="PlaneType">
		<xsd:sequence>
			<xsd:element name="Chars" type="CharsType"/>
			<xsd:element name="Parameters" type="ParametersType"/>
		</xsd:sequence>
          <xsd:attribute name="model" type="xsd:string" use="required"/>
	  <xsd:attribute name="origin" type="xsd:string"/>
	  <xsd:attribute name="price" type="xsd:decimal"/>
 	</xsd:complexType>
	
	<xsd:complexType name="CharsType">
           <xsd:sequence>
		<xsd:element name="type">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="support"/>
					<xsd:enumeration value="bomber"/>
					<xsd:enumeration value="maintenance"/>
					<xsd:enumeration value="fighter"/>
					<xsd:enumeration value="interceptor"/>
					<xsd:enumeration value="scout"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:element>
		<xsd:element name="seats">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:maxExclusive value = "3"/>
					<xsd:minExclusive value = "0"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:element>
		<xsd:element name="ammo" type="xsd:boolean"/>
		<xsd:element name="rocket">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:maxExclusive value = "10"/>
					<xsd:minExclusive value = "0"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:element>
		<xsd:element name="radar" type="xsd:boolean"/>
           </xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="ParametersType">
             <xsd:sequence> 
		<xsd:element name="Length" type="xsd:decimal"/>
		<xsd:element name="Width" type="xsd:decimal"/>
		<xsd:element name="Height" type="xsd:decimal"/>
              </xsd:sequence>
	</xsd:complexType>
        
</xsd:schema>

=== slamgp/xml/xml/xml project/planes.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl"  href="planes.xsl"?>
<Planes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="planes.xsd">
    <Plane 	model = "mig 29" origin = "russia" price = "2000000" >
        <Chars>
            <type>fighter</type>
            <seats>1</seats>
            <ammo>true</ammo>
            <rocket>6</rocket>
            <radar>true</radar>
	</Chars>
        <Parameters>
            <Length>17.32</Length>
            <Width>11.36</Width>
            <Height>4.73</Height>
	</Parameters>
    </Plane>   
    <Plane 	model = "su 34" origin = "russia" price = "2000000" >
        <Chars>
            <type>bomber</type>
            <seats>2</seats>
            <ammo>true</ammo>
            <rocket>8</rocket>
            <radar>true</radar>
	</Chars>
        <Parameters>
            <Length>23.3</Length>
            <Width>14.7</Width>
            <Height>6.09 </Height>
		</Parameters>
    </Plane>  
        <Plane 	model = "f 16" origin = "usa" price = "3000000" >
        <Chars>
            <type>fighter</type>
            <seats>1</seats>
            <ammo>true</ammo>
            <rocket>8</rocket>
            <radar>true</radar>
		</Chars>
        <Parameters>
            <Length>14.52</Length>
            <Width>9.45</Width>
            <Height>5.01</Height>
		</Parameters>
    </Plane>  
</Planes>
